name: Check Docker Build
on:
  push:
    branches:
      - main
      - staging

jobs:
  docker-build:
    name: Test docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t flask_backend .

      - name: Build test docker image
        run: docker build -t flask_test -f Dockerfile.test .

      # - name: Run tests
      #   run: docker run flask_test
