name: Release
on:
  push:
    branches:
      - main

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/785169674792/locations/global/workloadIdentityPools/github-pool/providers/github-pool-provider
          service_account: github-actions@ml-web-scraping-367112.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
             europe-west3-docker.pkg.dev/ml-web-scraping-367112/ml-web-scraping/backend-app:${{ steps.get-tag.outputs.short_ref }}
             europe-west3-docker.pkg.dev/ml-web-scraping-367112/ml-web-scraping/backend-app:latest
